"""Feedback storage for public testing (SQLite and Postgres)."""

from __future__ import annotations

import json
import sqlite3
from typing import Any

try:
    import psycopg
    from psycopg.rows import dict_row
except Exception:  # pragma: no cover
    psycopg = None
    dict_row = None


def _is_postgres_db(db_path: str) -> bool:
    path = str(db_path).strip()
    return path.startswith("postgres://") or path.startswith("postgresql://")


def init_db(db_path: str) -> None:
    if _is_postgres_db(db_path):
        if psycopg is None:  # pragma: no cover
            raise RuntimeError("psycopg is required for Postgres feedback storage")
        with psycopg.connect(str(db_path).strip()) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    CREATE TABLE IF NOT EXISTS feedback (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        message TEXT NOT NULL,
                        rating INTEGER,
                        contact TEXT,
                        context_json TEXT,
                        user_agent TEXT
                    )
                    """
                )
            conn.commit()
        return

    with sqlite3.connect(db_path) as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS feedback (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT NOT NULL DEFAULT (datetime('now')),
                message TEXT NOT NULL,
                rating INTEGER,
                contact TEXT,
                context_json TEXT,
                user_agent TEXT
            )
            """
        )
        conn.commit()


def save_feedback(
    db_path: str,
    *,
    message: str,
    rating: int | None = None,
    contact: str | None = None,
    context: dict[str, Any] | None = None,
    user_agent: str = "",
) -> int:
    context_json = json.dumps(context or {}, separators=(",", ":"), ensure_ascii=True)
    if _is_postgres_db(db_path):
        if psycopg is None:  # pragma: no cover
            raise RuntimeError("psycopg is required for Postgres feedback storage")
        with psycopg.connect(str(db_path).strip()) as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    INSERT INTO feedback (message, rating, contact, context_json, user_agent)
                    VALUES (%s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (message, rating, contact, context_json, user_agent[:512]),
                )
                row = cur.fetchone()
            conn.commit()
            return int(row[0]) if row else 0

    with sqlite3.connect(db_path) as conn:
        cur = conn.execute(
            """
            INSERT INTO feedback (message, rating, contact, context_json, user_agent)
            VALUES (?, ?, ?, ?, ?)
            """,
            (message, rating, contact, context_json, user_agent[:512]),
        )
        conn.commit()
        return int(cur.lastrowid)


def list_recent(db_path: str, limit: int = 50) -> list[dict[str, Any]]:
    safe_limit = max(1, min(limit, 200))
    if _is_postgres_db(db_path):
        if psycopg is None:  # pragma: no cover
            raise RuntimeError("psycopg is required for Postgres feedback storage")
        with psycopg.connect(str(db_path).strip()) as conn:
            with conn.cursor(row_factory=dict_row) as cur:
                cur.execute(
                    """
                    SELECT id, created_at, message, rating, contact, context_json
                    FROM feedback
                    ORDER BY id DESC
                    LIMIT %s
                    """,
                    (safe_limit,),
                )
                rows = cur.fetchall()
    else:
        with sqlite3.connect(db_path) as conn:
            conn.row_factory = sqlite3.Row
            rows = conn.execute(
                """
                SELECT id, created_at, message, rating, contact, context_json
                FROM feedback
                ORDER BY id DESC
                LIMIT ?
                """,
                (safe_limit,),
            ).fetchall()

    out: list[dict[str, Any]] = []
    for row in rows:
        try:
            context = json.loads((row["context_json"] if isinstance(row, dict) else row["context_json"]) or "{}")
        except json.JSONDecodeError:
            context = {}
        rid = row["id"] if isinstance(row, dict) else row["id"]
        created = row["created_at"] if isinstance(row, dict) else row["created_at"]
        msg = row["message"] if isinstance(row, dict) else row["message"]
        rating = row["rating"] if isinstance(row, dict) else row["rating"]
        contact = row["contact"] if isinstance(row, dict) else row["contact"]
        out.append(
            {
                "id": rid,
                "created_at": str(created),
                "message": msg,
                "rating": rating,
                "contact": contact,
                "context": context,
            }
        )
    return out
